# Generated by Django 4.2.15 on 2025-06-23 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusMensagemWhatsApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=100, unique=True, verbose_name='ID da Mensagem')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone (WhatsApp ID)')),
                ('status', models.CharField(choices=[('sent', 'Enviado'), ('delivered', 'Entregue'), ('read', 'Lido'), ('failed', 'Falha'), ('deleted', 'Deletado')], max_length=20, verbose_name='Status')),
                ('descricao_erro', models.TextField(blank=True, null=True, verbose_name='Descrição do erro')),
                ('data_status', models.DateTimeField(verbose_name='Data do status')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Registrado em')),
            ],
            options={
                'verbose_name': 'Status da Mensagem WhatsApp',
                'verbose_name_plural': 'Status das Mensagens WhatsApp',
                'ordering': ['-data_status'],
            },
        ),
    ]
