# Generated by Django 5.0.1 on 2024-08-11 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("solicitacao", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Execucao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("n_execucao", models.IntegerField(blank=True, null=True)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                ("che_maq_paradara", models.BooleanField(default=False)),
                ("exec_maq_parada", models.BooleanField(default=False)),
                ("apos_exec_maq_parada", models.BooleanField(default=False)),
                (
                    "ordem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execucao_solicitacao",
                        to="solicitacao.solicitacao",
                    ),
                ),
            ],
            options={
                "unique_together": {("ordem", "n_execucao")},
            },
        ),
        migrations.CreateModel(
            name="MaquinaParada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                (
                    "execucao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execucao_maquinaparada",
                        to="execucao.execucao",
                    ),
                ),
            ],
        ),
    ]
