# Generated by Django 5.0.1 on 2024-08-11 22:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("execucao", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="execucao",
            name="data_fim",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="execucao",
            name="data_inicio",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="maquinaparada",
            name="data_fim",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="maquinaparada",
            name="data_inicio",
            field=models.DateTimeField(),
        ),
    ]
