# Generated by Django 4.2.15 on 2024-08-19 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitacao', '0001_initial'),
        ('execucao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinaparada',
            name='ordem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordem_maquinaparada', to='solicitacao.solicitacao'),
        ),
        migrations.AddField(
            model_name='execucao',
            name='ordem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucao_solicitacao', to='solicitacao.solicitacao'),
        ),
        migrations.AlterUniqueTogether(
            name='execucao',
            unique_together={('ordem', 'n_execucao')},
        ),
    ]
