# Generated by Django 4.2.15 on 2024-08-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execucao', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='execucao',
            name='status',
            field=models.CharField(choices=[('em_espera', 'Em espera'), ('em_execucao', 'Em execuçao'), ('aguardando_material', 'Aguardando material'), ('finalizada', 'Finalizada')], default='em_espera', max_length=40),
        ),
    ]
