# Generated by Django 5.0.1 on 2024-08-11 22:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "execucao",
            "0002_alter_execucao_data_fim_alter_execucao_data_inicio_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="execucao",
            old_name="che_maq_paradara",
            new_name="che_maq_parada",
        ),
    ]
