# Generated by Django 5.0.1 on 2024-08-11 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("execucao", "0003_rename_che_maq_paradara_execucao_che_maq_parada"),
        ("solicitacao", "0002_alter_solicitacao_data_abertura"),
    ]

    operations = [
        migrations.AddField(
            model_name="maquinaparada",
            name="ordem",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ordem_maquinaparada",
                to="solicitacao.solicitacao",
            ),
            preserve_default=False,
        ),
    ]
