# Generated by Django 5.0.1 on 2024-08-11 22:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("execucao", "0004_maquinaparada_ordem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="maquinaparada",
            name="execucao",
        ),
    ]
