# Generated by Django 5.0.1 on 2024-08-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("execucao", "0005_remove_maquinaparada_execucao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maquinaparada",
            name="data_fim",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
