# Generated by Django 4.2.15 on 2024-08-26 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0009_solicitacao_planejada'),
        ('execucao', '0005_execucao_ultima_atualizacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoFinalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_finalizacao', models.DateTimeField(auto_now_add=True)),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordem_finalizada', to='solicitacao.solicitacao')),
            ],
        ),
    ]
