# Generated by Django 4.2.15 on 2024-08-26 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('execucao', '0006_solicitacaofinalizada'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SolicitacaoFinalizada',
        ),
    ]
