# Generated by Django 4.2.15 on 2024-09-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execucao', '0007_delete_solicitacaofinalizada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execucao',
            name='status',
            field=models.CharField(choices=[('aguardando_atendimento', 'Aguardando atendimento'), ('em_espera', 'Em espera'), ('em_execucao', 'Em execuçao'), ('aguardando_material', 'Aguardando material'), ('finalizada', 'Finalizada')], default='em_espera', max_length=40),
        ),
    ]
