# Generated by Django 4.2.15 on 2024-09-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0011_alter_operador_status'),
        ('execucao', '0008_alter_execucao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execucao',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='execucao',
            name='operador',
            field=models.ManyToManyField(blank=True, to='cadastro.operador'),
        ),
    ]
