# Generated by Django 4.2.15 on 2024-10-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execucao', '0009_alter_execucao_observacao_alter_execucao_operador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infosolicitacao',
            name='tipo_manutencao',
            field=models.CharField(choices=[('corretiva', 'Corretiva'), ('preditiva', 'Preditiva'), ('preventiva', ' Preventiva'), ('preventiva_programada', ' Preventiva programada'), ('apoio', 'Apoio'), ('projetos', 'Projetos'), ('sesmt', 'SESMT'), ('corretiva_programada', 'Corretiva programada')], max_length=40),
        ),
    ]
