# Generated by Django 4.2.15 on 2024-10-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0016_pecautilizada'),
        ('execucao', '0010_alter_infosolicitacao_tipo_manutencao'),
    ]

    operations = [
        migrations.AddField(
            model_name='execucao',
            name='peca_utilizada',
            field=models.ManyToManyField(blank=True, null=True, to='cadastro.pecautilizada'),
        ),
        migrations.AddField(
            model_name='execucao',
            name='quantidade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
