# Generated by Django 4.2.15 on 2024-10-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0017_checklist_itenschecklist'),
        ('execucao', '0011_execucao_peca_utilizada_execucao_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execucao',
            name='peca_utilizada',
            field=models.ManyToManyField(blank=True, to='cadastro.pecautilizada'),
        ),
    ]
