# Generated by Django 4.2.15 on 2024-11-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execucao', '0012_alter_execucao_peca_utilizada'),
    ]

    operations = [
        migrations.RenameField(
            model_name='execucao',
            old_name='quantidade',
            new_name='paplus',
        ),
        migrations.RemoveField(
            model_name='execucao',
            name='peca_utilizada',
        ),
        migrations.AddField(
            model_name='execucao',
            name='ph_agua',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='execucao',
            name='pvlye',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='execucao',
            name='tratamento_ete',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
