# Generated by Django 4.2.15 on 2024-08-19 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=100, null=True)),
                ('apelido', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('salario', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaquinaLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('equipamento_em_falha', models.CharField(choices=[('maquina_de_solda', 'Máquina de Solda'), ('monovia', 'Monovia'), ('ferramentas', 'Ferramentas'), ('robo_kuka', 'SO-RB-01 - ROBÔ - KUKA'), ('outros', 'Outros')], max_length=200)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.maquina')),
            ],
        ),
        migrations.AddField(
            model_name='maquina',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maquina_setor', to='cadastro.setor'),
        ),
    ]
