# Generated by Django 4.2.15 on 2024-08-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinalocal',
            name='equipamento_em_falha',
            field=models.CharField(blank=True, choices=[('maquina_de_solda', 'Máquina de Solda'), ('monovia', 'Monovia'), ('ferramentas', 'Ferramentas'), ('robo_kuka', 'SO-RB-01 - ROBÔ - KUKA'), ('outros', 'Outros')], max_length=200, null=True),
        ),
    ]
