# Generated by Django 4.2.15 on 2024-08-20 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0005_remove_solicitacao_maquina_local'),
        ('cadastro', '0002_alter_maquinalocal_equipamento_em_falha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaquinaLocal',
        ),
    ]
