# Generated by Django 4.2.15 on 2024-08-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_delete_maquinalocal'),
    ]

    operations = [
        migrations.AddField(
            model_name='operador',
            name='area',
            field=models.CharField(choices=[('predial', 'Predial'), ('producao', 'Produção')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
