# Generated by Django 4.2.15 on 2024-08-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_operador_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
    ]
