# Generated by Django 4.2.15 on 2024-08-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_maquina_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='area',
            field=models.CharField(choices=[('predial', 'Predial'), ('producao', 'Produção')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maquina',
            name='tombamento',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
