# Generated by Django 4.2.15 on 2024-08-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_maquina_area_maquina_tombamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='tombamento',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='maquina',
            constraint=models.UniqueConstraint(fields=('codigo', 'tombamento', 'area'), name='unique_maquina'),
        ),
    ]
