# Generated by Django 4.2.15 on 2024-08-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_alter_maquina_codigo_alter_maquina_tombamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='criticidade',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
