# Generated by Django 4.2.15 on 2024-09-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_maquina_criticidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
