# Generated by Django 4.2.15 on 2024-09-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0010_tipotarefas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operador',
            name='status',
            field=models.CharField(blank=True, choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], max_length=20, null=True),
        ),
    ]
