# Generated by Django 4.2.15 on 2024-09-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0011_alter_operador_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='tipo',
            field=models.CharField(blank=True, choices=[('monovia', 'Monovia')], max_length=20, null=True),
        ),
    ]
