# Generated by Django 4.2.15 on 2024-09-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0012_maquina_tipo'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='maquina',
            name='unique_maquina',
        ),
        migrations.AddConstraint(
            model_name='maquina',
            constraint=models.UniqueConstraint(fields=('codigo', 'area'), name='unique_maquina'),
        ),
    ]
