# Generated by Django 4.2.15 on 2024-10-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0014_remove_maquina_unique_maquina_maquina_unique_maquina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='tombamento',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
