# Generated by Django 4.2.15 on 2024-11-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0018_operador_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipotarefas',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
