# Generated by Django 4.2.15 on 2025-02-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0019_alter_tipotarefas_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipotarefas',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
