# Generated by Django 4.2.16 on 2025-03-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0021_alter_maquina_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="maquina",
            name="maquina_critica",
            field=models.BooleanField(default=False),
        ),
    ]
