# Generated by Django 6.0.3 on 2026-03-17 10:43

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0022_maquina_maquina_critica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('ativo', models.BooleanField(default=True)),
                ('token_publico', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists_formulario_criados', to=settings.AUTH_USER_MODEL)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_formularios', to='cadastro.maquina')),
            ],
            options={
                'ordering': ('-atualizado_em',),
            },
        ),
        migrations.CreateModel(
            name='ChecklistFormularioVersao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('titulo', models.CharField(max_length=160)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists_versao_criados', to=settings.AUTH_USER_MODEL)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versoes', to='cadastro.checklistformulario')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_versoes', to='cadastro.maquina')),
            ],
            options={
                'ordering': ('-numero',),
                'unique_together': {('formulario', 'numero')},
            },
        ),
        migrations.AddField(
            model_name='checklistformulario',
            name='versao_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cadastro.checklistformularioversao'),
        ),
        migrations.CreateModel(
            name='ChecklistPergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('texto', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('input', 'Input'), ('single_choice', 'Escolha unica'), ('multiple_choice', 'Multipla escolha')], max_length=20)),
                ('obrigatoria', models.BooleanField(default=True)),
                ('versao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='cadastro.checklistformularioversao')),
            ],
            options={
                'ordering': ('ordem', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ChecklistPerguntaOpcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=255)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='cadastro.checklistpergunta')),
            ],
            options={
                'ordering': ('ordem', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ChecklistResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_referencia', models.DateField(default=datetime.date.today)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('imagem', models.ImageField(upload_to='checklists/respostas/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas', to='cadastro.checklistformulario')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_respostas', to=settings.AUTH_USER_MODEL)),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklist_respostas', to='cadastro.maquina')),
                ('versao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas', to='cadastro.checklistformularioversao')),
            ],
            options={
                'ordering': ('-criado_em',),
            },
        ),
        migrations.CreateModel(
            name='ChecklistRespostaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_resposta', models.TextField(blank=True, null=True)),
                ('opcoes_selecionadas', models.JSONField(blank=True, default=list)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respostas_itens', to='cadastro.checklistpergunta')),
                ('resposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='cadastro.checklistresposta')),
            ],
            options={
                'unique_together': {('resposta', 'pergunta')},
            },
        ),
    ]
