# Generated by Django 6.0.3 on 2026-03-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0023_checklistformulario_checklistformularioversao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistresposta',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='checklists/respostas/'),
        ),
    ]
