# Generated by Django 4.2.15 on 2026-05-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0025_checklistrelatoriodestinatario'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(max_length=20)),
                ('responsavel', models.CharField(blank=True, max_length=200, null=True)),
                ('data_criacao', models.DateField()),
                ('hora_criacao', models.TimeField()),
                ('data_baixa', models.DateField(blank=True, null=True)),
                ('fornecedor_codigo', models.CharField(blank=True, max_length=200, null=True)),
                ('fornecedor_documento', models.CharField(blank=True, max_length=20, null=True)),
                ('codigo_produto', models.CharField(blank=True, max_length=200, null=True)),
                ('descricao_produto', models.CharField(blank=True, max_length=500, null=True)),
                ('data_aprovacao', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('importado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-data_criacao', 'numero_pedido'),
            },
        ),
    ]
