# Generated by Django 4.2.15 on 2026-07-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0026_pedidocompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='nao_considerar_parada',
            field=models.BooleanField(default=False, help_text='Se marcado, esta máquina nunca é registrada como parada (MaquinaParada), mesmo que uma execução indique parada.', verbose_name='Não considerar parada (exceção)'),
        ),
    ]
