# Generated by Django 4.2.15 on 2026-09-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0027_maquina_nao_considerar_parada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='criticidade',
            field=models.CharField(blank=True, choices=[('na', 'N/A'), ('a', 'A'), ('b', 'B'), ('c', 'C')], default='na', max_length=2),
        ),
    ]
