# Generated by Django 4.2.15 on 2024-08-26 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0008_alter_maquina_codigo_alter_maquina_tombamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoPreventiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('periodicidade', models.IntegerField(help_text='Número de dias entre cada execução')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_preventiva', to='cadastro.maquina')),
            ],
        ),
        migrations.CreateModel(
            name='TarefaPreventiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('responsabilidade', models.CharField(choices=[('eletrica', 'Elétrica'), ('mecanica', 'Mecânica'), ('predial', 'Predial')], max_length=20)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_preventiva', to='preventiva.planopreventiva')),
            ],
        ),
        migrations.CreateModel(
            name='ExecucaoPreventiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucao_plano', to='preventiva.planopreventiva')),
            ],
        ),
    ]
