# Generated by Django 4.2.15 on 2024-08-26 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0009_solicitacao_planejada'),
        ('preventiva', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoPreventiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finalizada', models.BooleanField(default=False)),
                ('data', models.DateField()),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preventiva_solicitacao', to='solicitacao.solicitacao')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucao_plano', to='preventiva.planopreventiva')),
            ],
        ),
        migrations.DeleteModel(
            name='ExecucaoPreventiva',
        ),
    ]
