# Generated by Django 4.2.15 on 2024-08-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventiva', '0002_solicitacaopreventiva_delete_execucaopreventiva'),
    ]

    operations = [
        migrations.AddField(
            model_name='planopreventiva',
            name='abertura_automativa',
            field=models.BooleanField(default=True),
        ),
    ]
