# Generated by Django 4.2.15 on 2024-08-27 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preventiva', '0003_planopreventiva_abertura_automativa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planopreventiva',
            old_name='abertura_automativa',
            new_name='abertura_automatica',
        ),
    ]
