# Generated by Django 4.2.15 on 2024-10-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventiva', '0006_alter_planopreventiva_dias_antecedencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='planopreventiva',
            name='area',
            field=models.CharField(choices=[('producao', 'Produção'), ('predial', 'Predial')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
