# Generated by Django 4.2.15 on 2024-11-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventiva', '0007_planopreventiva_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='planopreventiva',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
