# Generated by Django 4.2.15 on 2025-03-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preventiva', '0009_planopreventiva_data_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='planopreventiva',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
