# Generated by Django 4.2.15 on 2024-08-19 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('maq_parada', models.BooleanField(default=False)),
                ('equipamento_em_falha', models.CharField(choices=[('maquina_de_solda', 'Máquina de Solda'), ('monovia', 'Monovia'), ('ferramentas', 'Ferramentas'), ('robo_kuka', 'SO-RB-01 - ROBÔ - KUKA'), ('outros', 'Outros')], max_length=200)),
                ('setor_maq_solda', models.CharField(choices=[('laterais', 'Laterais'), ('eixos', 'Eixos'), ('icamentos', 'Içamentos'), ('plataforma', 'Plataforma'), ('chassi', 'Chassi'), ('tanque', 'Tanque'), ('cacamba', 'Caçamba'), ('serralheria', 'Serralheria')], max_length=200)),
                ('impacto_producao', models.CharField(choices=[('alto', 'Alto'), ('medio', 'Médio'), ('baixo', 'Baixo')], max_length=20)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.maquina')),
                ('maquina_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.maquinalocal')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.setor')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='fotos/')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='solicitacao.solicitacao')),
            ],
        ),
    ]
