# Generated by Django 5.0.1 on 2024-08-11 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("solicitacao", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitacao",
            name="data_abertura",
            field=models.DateTimeField(),
        ),
    ]
