# Generated by Django 4.2.15 on 2024-08-19 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_alter_maquinalocal_equipamento_em_falha'),
        ('solicitacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='equipamento_em_falha',
            field=models.CharField(blank=True, choices=[('maquina_de_solda', 'Máquina de Solda'), ('monovia', 'Monovia'), ('ferramentas', 'Ferramentas'), ('robo_kuka', 'SO-RB-01 - ROBÔ - KUKA'), ('outros', 'Outros')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='maquina_local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.maquinalocal'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='setor_maq_solda',
            field=models.CharField(blank=True, choices=[('laterais', 'Laterais'), ('eixos', 'Eixos'), ('icamentos', 'Içamentos'), ('plataforma', 'Plataforma'), ('chassi', 'Chassi'), ('tanque', 'Tanque'), ('cacamba', 'Caçamba'), ('serralheria', 'Serralheria')], max_length=200, null=True),
        ),
    ]
