# Generated by Django 4.2.15 on 2024-08-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0003_solicitacao_codigo_ferramenta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='descricao',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
