# Generated by Django 4.2.15 on 2024-08-20 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0004_solicitacao_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='maquina_local',
        ),
    ]
