# Generated by Django 4.2.15 on 2024-08-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0005_remove_solicitacao_maquina_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='tipo_ferramenta',
            field=models.CharField(blank=True, choices=[('esmerilhadeira', 'Esmerilhadeira'), ('tocha', 'Tocha')], max_length=20, null=True),
        ),
    ]
