# Generated by Django 4.2.15 on 2024-08-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0006_alter_solicitacao_tipo_ferramenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='area',
            field=models.CharField(choices=[('predial', 'Predial'), ('producao', 'Producao')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='impacto_producao',
            field=models.CharField(blank=True, choices=[('alto', 'Alto'), ('medio', 'Médio'), ('baixo', 'Baixo')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='maq_parada',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
