# Generated by Django 4.2.15 on 2024-08-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0007_solicitacao_area_alter_solicitacao_impacto_producao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='maq_parada',
            field=models.BooleanField(default=False),
        ),
    ]
