# Generated by Django 4.2.15 on 2024-08-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0009_solicitacao_planejada'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='prioridade',
            field=models.CharField(blank=True, choices=[('alto', 'Alto'), ('medio', 'Médio'), ('baixo', 'Baixo')], max_length=20, null=True),
        ),
    ]
