# Generated by Django 4.2.15 on 2024-09-09 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0010_tipotarefas'),
        ('solicitacao', '0010_solicitacao_prioridade'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='tarefa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.tipotarefas'),
        ),
    ]
