# Generated by Django 4.2.15 on 2024-09-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0013_alter_solicitacao_comentario_manutencao'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(blank=True, choices=[('aprovar', 'Aprovar'), ('rejeitar', 'Rejeitar')], max_length=20, null=True),
        ),
    ]
