# Generated by Django 4.2.15 on 2024-10-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0014_solicitacao_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='satisfacao_registrada',
            field=models.BooleanField(default=False),
        ),
    ]
