# Generated by Django 4.2.15 on 2024-10-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0015_solicitacao_satisfacao_registrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='status_andamento',
            field=models.CharField(choices=[('aguardando_atendimento', 'Aguardando atendimento'), ('em_espera', 'Em espera'), ('em_execucao', 'Em execuçao'), ('aguardando_material', 'Aguardando material'), ('finalizada', 'Finalizada')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
