# Generated by Django 4.2.15 on 2024-10-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0016_solicitacao_status_andamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='status_andamento',
            field=models.CharField(choices=[('aguardando_atendimento', 'Aguardando atendimento'), ('em_espera', 'Em espera'), ('em_execucao', 'Em execuçao'), ('aguardando_material', 'Aguardando material'), ('finalizada', 'Finalizada')], default='aguardando_atendimento', max_length=30),
        ),
    ]
