# Generated by Django 5.0.1 on 2024-10-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("solicitacao", "0017_alter_solicitacao_status_andamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitacao",
            name="programacao",
            field=models.DateField(blank=True, null=True),
        ),
    ]
