# Generated by Django 5.0.1 on 2024-10-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("solicitacao", "0018_solicitacao_programacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitacao",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("aprovar", "Aprovar"), ("rejeitar", "Rejeitar")],
                db_index=True,
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="solicitacao",
            name="status_andamento",
            field=models.CharField(
                choices=[
                    ("aguardando_atendimento", "Aguardando atendimento"),
                    ("em_espera", "Em espera"),
                    ("em_execucao", "Em execuçao"),
                    ("aguardando_material", "Aguardando material"),
                    ("finalizada", "Finalizada"),
                ],
                db_index=True,
                default="aguardando_atendimento",
                max_length=30,
            ),
        ),
    ]
