# Generated by Django 4.2.15 on 2024-11-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0021_set_id_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
