# Generated by Django 4.2.15 on 2024-10-24 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0022_alter_solicitacao_descricao'),
    ]

    operations = [
        migrations.RunSQL("ALTER SEQUENCE solicitacao_solicitacao_id_seq RESTART WITH 4000;")
    ]
