# Generated by Django 4.2.15 on 2024-11-11 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0018_operador_telefone'),
        ('solicitacao', '0024_alter_solicitacao_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='setor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cadastro.setor'),
            preserve_default=False,
        ),
    ]
