# Generated by Django 4.2.15 on 2024-12-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0025_alter_solicitacao_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='setor_maq_solda',
            field=models.CharField(blank=True, choices=[('laterais', 'Laterais'), ('eixos', 'Eixos'), ('icamentos', 'Içamentos'), ('plataforma', 'Plataforma'), ('chassi', 'Chassi'), ('tanque', 'Tanque'), ('cacamba', 'Caçamba'), ('serralheria', 'Serralheria'), ('fueiro', 'Fueiro')], max_length=200, null=True),
        ),
    ]
