# Generated by Django 4.2.16 on 2025-03-27 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cadastro", "0021_alter_maquina_tipo"),
        ("solicitacao", "0026_alter_solicitacao_setor_maq_solda"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solicitacao",
            name="maquina",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cadastro.maquina",
            ),
        ),
    ]
