# Generated by Django 4.2.15 on 2025-11-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0028_alter_solicitacao_maquina'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='motivo_atraso',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
