# Generated by Django 4.2.15 on 2026-05-18 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solicitacao', '0029_solicitacao_motivo_atraso'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='rejeitado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_rejeitadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
