# Generated by Django 4.2.15 on 2026-09-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0031_reprogramacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='rejeitado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
