# Generated by Django 4.2.15 on 2026-09-16 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacao', '0032_solicitacao_rejeitado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='duplicada_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicatas', to='solicitacao.solicitacao'),
        ),
    ]
