# Generated by Django 4.2.15 on 2024-08-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0002_alter_funcionario_tipo_acesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='area',
            field=models.CharField(blank=True, choices=[('producao', 'Produção'), ('predial', 'Predial')], max_length=50, null=True),
        ),
    ]
