# Generated by Django 4.2.15 on 2024-10-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0004_alter_funcionario_tipo_acesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
