# Generated by Django 4.2.15 on 2024-10-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('funcionario', '0005_funcionario_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Os grupos aos quais o funcionário pertence.', related_name='funcionario_set', to='auth.group', verbose_name='grupos'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissões específicas para este funcionário.', related_name='funcionario_user_set', to='auth.permission', verbose_name='permissões de funcionário'),
        ),
    ]
