# Generated by Django 4.2.15 on 2024-10-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0006_alter_funcionario_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
